security:
    # Password hashing configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username  # Use 'username' instead of 'email'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider  # Correctly reference the provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                username_parameter: _username  # Ensure it matches your form field name
                password_parameter: _password
                default_target_path: app_home_page  # Redirect after login
            logout:
                path: app_logout
                target: app_login

    # Define access control rules
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4   # Lower cost for tests
                time_cost: 3
                memory_cost: 10
